language: python

python:
    - '3.6'

cache: pip

install:
    - pip install --requirement requirements.txt
    - pip install --requirement requirements.test.txt

script:
    - make lint  # pylint
    - make test  # incl. coverage

notifications:
    email: false
    slack:
        rooms:
            - shitoucho:7SlzoqgpXjRB7M7u8kgEoYSc#music-results
