language: python
python:
    - '3.6'
install:
    - pip install --requirement requirements.txt
    - pip install --requirement requirements.test.txt
script:
    - make lint  # pylint
    - make test  # incl. coverage
